package main

import (
	"crypto/sha256"
	"encoding/base32"
	"fmt"

	"github.com/blues-lab/totp-app-analysis-public/utils"
)

const (
	password = "rRmhyojrhMyAFFD2_sEdXwiyJfTexRBr"

	// Copy/pasted from the network traffic. The JSON object has field
	// `passphrase` with child field `private_key`.
	appPrivateKeyCiphertextBase32 = "R7DSWLWWPK4MRW32DVRUO6ADLMULXZWYKWPFIKVD6HPQQYRSM46IQ33667TJT6CEARMWDVNZRG5Z3USSIA3YIKPKU7L5ICU3TC2MDMGVQGAI6I4AWLNEGRLNYESI73RIYP4Y3MGLSD24RKHYZO6HBWHIP34HCBYIOJUBKXVXWQU53SQ3LCHIQMA2LVUJTE6LPS6L3FBNEPJTLRJRFTWLVSTHY7W562VVUM2IP6NPJ5YY5DZBR5CTKG7ZJHXZCZ2SGSBGJKHSV7GNGE3WB5OXSLDW3CLPQV5EQLUQ4CHH5JFII7V3647HV7JZKO4FDFN3OSGEFGNWMGSP3PLZK2FMQHHMTBNL2RJTW464M5ZEARAMCDENLOGXAY6SEMIX2K73LSSVGDPRS5BSACIBN6O4DJBDQIMTACNXFBILB6TT2GADAAXKBJRO6GZFUHCIOPW73JSSERTZK3F3XGNJLL5N26GGWZDJ4Y44466E2U4EADH2HL3WBRMUM3USUO6GN2LEGACCP6D2YZR5HX67YT3TWSLYY54ASG6QUBTZSMTQJIXQOTGHJGQDVZ5AZICZ6KYYSCPTIMH2PBPIKRNT7GHOKQSPKYDDHKBAEXIYQREJIWS4EJ46MM4552HQYYI54BMIXJSLS2I665LUUKBVLLKUWT2UO6WQDXR3XJBVSRWFIZRBID6JQICYYVEFZDWL62KXYIHDPXJ5O7YXLZUSHXKSD6SSHF7AKJNYY7ZGDRZ2BS4D4UQR4BDXSGQRGQS7GGH2GINVAA7ZWUJXSO4YDP4DCOEZKTYQXFYSTWVBW4JZAHMY53ISCNALA4P5NCA5M3N33MISAHGPNN75WLVPGWOVJXDOLDHKFK5LBTUR3CPRLPUVF2EXOUDQZMPF2TBUR26ZPEFWM6VJNDFUYTT5KWDD5TWW3V5MMQBCJKPOYOP6OMMNZM7E46QO3GC7LCVS5FU3MI4FCKN2NQTBKGZRCK75O6S5NA7AHSXQSOSQ2Z3E5QCXYAFMUOX5BUTGBHQOOWGZITAWHDLJ455I22LSANOWDULD3ZLPC5IGENIS2W6EP7BAZAG3DEPWE73WPIDYBF5N6FZ4IIWTDFZLXIDDTXCMXGS35JYANF76T6D6INUY7Y6P2DQG4BGMJZSW4LKJLIVI2HX4KSCOCJYKYBWZNW3T6OGCTTDTOZBJ2QYVKE2WTM33UWLVWAAPME4WYY66LOPHVQAMBZY54O35HBFGGTEEYWBYLGPEW3PE5KLXNT3C4PQKCI5ZBERUGUXOCJMYZA2DVH67QH24UU6BJJZCBAOY5ANFPOT7DVCL5VXLXJU2WGDCDFVZNBX3QVHDEEUMUR2PP5ITPSCB5Q5DJMTOH7CGLXPJUTIGNJROOOQW5OI="

	// Copy/pasted from the network traffic. There is a JSON array named
	// `tpsecret_all` and each object in the array has a field called `app_secret`.
	qrCode1TotpCiphertextBase32 = "GLUEKWXJQCWKMIORCAB3HJLGVO4QKD7FCBQRKYKT2UFYWOAZO54DYQPLXGLNL5FVYOBWJOMB7XTVKZLGH2S2IRPDB6YUT6RXDYMNMX6M4ZIGLCMTGL2HDHWL2GWHZM66"
	qrCode2TotpCiphertextBase32 = "GLUEKWXJQCWKMIORCAB3HJLGVO4QKD7FCBQRKYKT2UFYWOAZO54DYQPLXGLNL5FVYOBWJOMB7XTVLU2INMHOYV7LSYJOWPFHE4LPEYOM4ZIGLCMTGL2HDHWL2GWHZM66"
)

func decryptTotpSecret(
	password string,
	appPrivateKeyCiphertextBase32 string,
	totpCiphertextBase32 string) []byte {

	passwordBytes := []byte(password)

	// The app uses a single round of SHA256 as a KDF.
	keyDerivedFromPassword := sha256.Sum256(passwordBytes)

	// Base32 decode the app private key.
	privateKeyCiphertextBytes, err := base32.StdEncoding.DecodeString(appPrivateKeyCiphertextBase32)
	if err != nil {
		panic(err)
	}

	// Decrypt the app private key.
	appPrivateKeyBytes := utils.DecryptAesEcbPaddedWithPKCS7(
		privateKeyCiphertextBytes,
		keyDerivedFromPassword[:])

	// The app uses a single round of SHA256 as a KDF. Derive the TOTP backup key
	// from the decrypted app private key. This unusual multi-level encryption
	// does not provide any additional security.
	totpBackupKeyBytes := sha256.Sum256(appPrivateKeyBytes)

	totpCiphertextBytes, err := base32.StdEncoding.DecodeString(totpCiphertextBase32)
	if err != nil {
		panic(err)
	}

	// Decrypt the TOTP backup.
	totpPlaintextBytes := utils.DecryptAesEcbPaddedWithPKCS7(
		totpCiphertextBytes,
		totpBackupKeyBytes[:])

	return totpPlaintextBytes
}

func main() {
	totpSecret1 := decryptTotpSecret(
		password,
		appPrivateKeyCiphertextBase32,
		qrCode1TotpCiphertextBase32)
	fmt.Printf("TOTP Secret 1 = %s\n", totpSecret1)

	totpSecret2 := decryptTotpSecret(
		password,
		appPrivateKeyCiphertextBase32,
		qrCode2TotpCiphertextBase32)
	fmt.Printf("TOTP Secret 2 = %s\n", totpSecret2)
}
